name: Build and Deploy to GitHub Pages Repo

on:
  push:
    branches: [main]  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install Dependencies
      run: npm ci

    - name: Build App
      run: npm run build

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Deploy to Pages Repo
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        cd dist
        git init
        git remote add origin git@github.com:BradAlmighty/bradalmighty.github.io.git
        git checkout -b main  # or gh-pages if that's your default branch
        git add .
        git commit -m "Deploy from source repo"
        git push -f origin main